apiVersion: v1
kind: Service
metadata:
  name: {{ include "manticoresearch.fullname" . }}-worker-svc
  labels:
    name: {{ include "manticoresearch.fullname" . }}-worker-svc
    {{- include "manticoresearch.labels" . | nindent 4 }}
spec:
  clusterIP: "None"
  ports:
    - port: {{ .Values.worker.service.ql.port }}
      targetPort: {{ .Values.worker.service.ql.targetPort }}
      name: ql
    - port: {{ .Values.worker.service.http.port }}
      targetPort: {{ .Values.worker.service.http.targetPort }}
      name: http
  selector:
    name: {{ include "manticoresearch.fullname" . }}-worker
