{{- if .Values.stopwords.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-stopwords
  labels:
    {{- include "manticoresearch.labels" . | nindent 4 }}
data:
  stopwords.txt:
    {{ toYaml .Values.stopwords.content | indent 4 }}
{{- end }}