apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "manticoresearch.fullname" . }}-worker-config
  labels:
    {{- include "manticoresearch.labels" . | nindent 4 }}
data:
  manticore.conf:
    {{ toYaml .Values.worker.config.content | indent 4 }}
  {{- if .Values.worker.stopwords.enabled }}
  stopwords.txt:
    {{ toYaml .Values.worker.stopwords.content | indent 4 }}
  {{- end }}
